version: 2
registries:
  fabric:
    url: "https://maven.fabricmc.net/"
    type: maven-repository
  gradle-plugins:
    url: "https://plugins.gradle.org/m2/"
    type: maven-repository
  maven-central:
    url: "https://repo1.maven.org/maven2/"
    type: maven-repository

updates:
  - package-ecosystem: gradle
    registries:
      - fabric
      - gradle-plugins
      - maven-central
    ignore:
      - dependency-name: me.melontini:dark-matter*
      - dependency-name: io.wispforest:owo-lib
      - dependency-name: me.melontini:handy-tests
    directory: /
    schedule:
      interval: weekly